language: go

sudo: false

env:
  - GO111MODULE=on

go:
  - 1.14.x

cache:
  directories:
    - $HOME/gopath/pkg/mod

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  app: dcard-shawnpeng
  api_key:
    secure: lRozXCNZB3qZ+EjvZc69dbziX9JOIZRnxYS/NJw9ixYKS1oB+WAPvHmT6Hh1p8ffjd2kxNvMaV7s4PMCVJXcYZfXQX5XheivFLszj4dG3HEj4WQ9fS4B62Dm0Rl0pR/R4E8pAEA3sG9H5x7imWBOiL7WA82u+s32RxdsGB/0MvPMmnB07satZdUP92ly2qtGYb4lUseadN0uP6pjyzUWCkKIS7jU+JiOp0/NWNjqkNxnOd+dDb7n+T0ULlMy5eohhB83h3LrauFIliFac8QS3GVDcS+1pfh+Qgeaa6rTA9XF+YqGGhW2qVWMFlLMVu9PhxylbX7dmPg6gEPiF4JV702Wr2RaygngCx1xTbgJlGM+LnsKN6gcLcdAK+aDJRdn2QNGNmINhJXB7hgiavsoST9xdvgp/HtoicTwcQzPi3fQrsbfJR6zr7b8PYsX+Do45tFGw1QxOEJciIMRydb4cnOtJ6UEa08wCxjMWrY9dqMst5nqnMT0hDNpaLjt6VmtOU58hMwefwi6XjXv8EGFu8lXVXAFiWYr9Y9o3cHNLxmxm/f5x35tVWon8sNF4QWbFI6jDEIyrHMTnoZLPXhkYE2Km8IvKDTy3uVTm7wDLyxXX9babPKgjqlbotMlk1hCxsPMh4TYGWpBjSfm1KIIfMiPmkc7PUd116ZQ8AHElaE=

